# Generated by Django 4.0.3 on 2022-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
