# Generated by Django 4.0.3 on 2022-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_date_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place_order',
            field=models.CharField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Delivery', 'Delivery')], max_length=100, null=True),
        ),
    ]
