# Generated by Django 4.0.3 on 2022-03-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_place_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_people', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('date_visit', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.table')),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiance', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=100, null=True)),
                ('food', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=100, null=True)),
                ('service', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=100, null=True)),
                ('suggestions', models.CharField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Call_waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.table')),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
    ]
