# Generated by Django 4.0.3 on 2022-03-31 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_detail_reservation_feedback_call_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orderitem'),
        ),
    ]
