# Generated by Django 4.0.3 on 2022-03-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_table_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='orderitem',
        ),
    ]
