# Generated by Django 4.0.3 on 2022-03-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
    ]
