# Generated by Django 4.0.3 on 2022-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_detail',
            old_name='state',
            new_name='zipcode',
        ),
    ]
