# Generated by Django 4.0.3 on 2022-04-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_state_contact_detail_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_detail',
            new_name='Restaurant',
        ),
    ]
