# Generated by Django 4.0.3 on 2022-04-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_waitstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='waitstaff',
        ),
    ]
