# Generated by Django 4.0.3 on 2022-05-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_reservation_phone_number_alter_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
