# Generated by Django 4.0.3 on 2022-05-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_feedback_customer_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
