# Generated by Django 4.0.3 on 2022-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_country_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
