# Generated by Django 4.0.3 on 2022-05-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_city_country_delete_student_delete_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='three_d_food',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
