# Generated by Django 4.0.3 on 2022-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_menu_three_d_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='three_d_food',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
