# Generated by Django 4.0.3 on 2022-06-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
