# Generated by Django 4.0.3 on 2022-06-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='address',
        ),
    ]
