# Generated by Django 4.0.3 on 2022-06-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_image_manager_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
