# Generated by Django 4.0.3 on 2022-06-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_profile_pic_manager_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/'),
        ),
    ]
