# Generated by Django 4.0.3 on 2022-06-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_waitstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waitstaff',
        ),
    ]
