# Generated by Django 4.0.3 on 2022-05-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
